version:  '3'
services:
  juice-shop:
    image: bkimminich/juice-shop
    ports:
        - '3000:3000'
  bwaap-vuln:
    image: raesene/bwapp
    ports:
        - '3001:80'
  dvwa-docker:
    image: vulnerables/web-dvwa
    ports:
        - '3002:80'
  nginx-reverse-proxy:
    ports:
      - '80:80'
    ipc: host
    image: checkpoint/infinity-next-nginx
    volumes:
      - ./nginx-reverse-proxy/default:/etc/nginx/conf.d/default.conf
  agent-container:
    ipc: host
    volumes:
      - ./agent-container/data:/etc/cp/data
      - ./agent-container/conf:/etc/cp/conf
      - ./agent-container/logs:/var/log/nano_agent
    image: checkpoint/infinity-next-nano-agent    
    command: ["/cp-nano-agent", "--token", "$TOKEN"]

